server:
  port: 8082

spring:
  application:
    name: driver-microservice

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      #      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      #      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: driver-ratings
      properties:
        string:
          json:
            trusted:
              packages: com.software.modsen.drivermicroservice.entities.rating

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/cab-aggregator-db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:98479847}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}

logging:
  level:
    com:
      netflix:
        eureka: off
        discovery: off