pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                scripts {
                    echo "Building project..."
                    sh 'mvn clean install -DskipTests'
                }
            }
        }

        stage('Linter') {
            steps {
                scripts {
                    echo "Linter"
                    sh 'mvn checkstyle:check'
                }
            }
        }

        stage('Test') {
            steps {
                scripts {
                    echo "Rinning tests..."
                    sh 'mvn test'
                }
            }
        }

        stage('Deploy') {
            steps {
                echo "Deploy project"
            }
        }
    }
}